// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package simple.grpcexample;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<simple.grpcexample.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  simple.grpcexample.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends simple.grpcexample.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  simple.grpcexample.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
